name: RandomX
version: '${project.version}'
main: wihy.randomx.Main
api-version: 1.18
authors: [ Wihy ]
description: an all in one plugin for Minecraft! essential for every minecraft server!

commands:
  tpa:
    usage: /tpa <text>
    description: /tpa
  tpaccept:
    usage: /tpaccept
    description: /tpaccept
  tplist:
    usage: /tplist
    description: /tplist
  builder:
    usage: /builder